import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum UserMode {
  developer,   // Accès complet (par défaut)
  technician,  // Configuration, Monitoring, Reconnecte
  user,        // Monitoring, Reconnecte
}

class AppSettings extends ChangeNotifier {
  static final AppSettings _instance = AppSettings._internal();
  factory AppSettings() => _instance;
  AppSettings._internal() {
    _loadPreferences();
  }

  ThemeMode _themeMode = ThemeMode.light;
  String _language = 'fr'; // 'fr', 'en', 'es', 'de', 'zh'
  UserMode _userMode = UserMode.developer; // Mode par défaut
  String _developerPassword = '1234';
  String _technicianPassword = '0000';
  
  // Paramètres MQTT
  String _mqttServer = '192.168.50.27';
  int _mqttPort = 1883;
  String _mqttUsername = 'fil_rouge';
  String _mqttPassword = '';

  // Paramètres de notifications
  bool _enableSuccessNotifications = true;
  bool _enableErrorNotifications = true;
  bool _enableLearningNotifications = true;

  ThemeMode get themeMode => _themeMode;
  String get language => _language;
  bool get isDarkMode => _themeMode == ThemeMode.dark;
  UserMode get userMode => _userMode;
  String get developerPassword => _developerPassword;
  String get technicianPassword => _technicianPassword;
  
  String get mqttServer => _mqttServer;
  int get mqttPort => _mqttPort;
  String get mqttUsername => _mqttUsername;
  String get mqttPassword => _mqttPassword;

  bool get enableSuccessNotifications => _enableSuccessNotifications;
  bool get enableErrorNotifications => _enableErrorNotifications;
  bool get enableLearningNotifications => _enableLearningNotifications;

  Future<void> _loadPreferences() async {
    final prefs = await SharedPreferences.getInstance();
    _themeMode = (prefs.getBool('isDarkMode') ?? false) ? ThemeMode.dark : ThemeMode.light;
    _language = prefs.getString('language') ?? 'fr';
    final userModeString = prefs.getString('userMode') ?? 'developer';
    _userMode = UserMode.values.firstWhere(
      (mode) => mode.name == userModeString,
      orElse: () => UserMode.developer,
    );
    _developerPassword = prefs.getString('developerPassword') ?? '1234';
    _technicianPassword = prefs.getString('technicianPassword') ?? '0000';
    _mqttServer = prefs.getString('mqttServer') ?? '192.168.50.27';
    _mqttPort = prefs.getInt('mqttPort') ?? 1883;
    _mqttUsername = prefs.getString('mqttUsername') ?? 'fil_rouge';
    _mqttPassword = prefs.getString('mqttPassword') ?? '';
    _enableSuccessNotifications = prefs.getBool('enableSuccessNotifications') ?? true;
    _enableErrorNotifications = prefs.getBool('enableErrorNotifications') ?? true;
    _enableLearningNotifications = prefs.getBool('enableLearningNotifications') ?? true;
    notifyListeners();
  }

  Future<void> toggleTheme() async {
    _themeMode = _themeMode == ThemeMode.light ? ThemeMode.dark : ThemeMode.light;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('isDarkMode', _themeMode == ThemeMode.dark);
    notifyListeners();
  }

  Future<void> setLanguage(String lang) async {
    _language = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', lang);
    notifyListeners();
  }

  Future<void> setUserMode(UserMode mode) async {
    _userMode = mode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('userMode', mode.name);
    notifyListeners();
  }

  bool verifyModePassword(UserMode mode, String password) {
    if (mode == UserMode.developer) return password == _developerPassword;
    if (mode == UserMode.technician) return password == _technicianPassword;
    return true;
  }

  Future<void> setDeveloperPassword(String password) async {
    _developerPassword = password;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('developerPassword', password);
    notifyListeners();
  }

  Future<void> setTechnicianPassword(String password) async {
    _technicianPassword = password;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('technicianPassword', password);
    notifyListeners();
  }

  String getUserModeLabel() {
    switch (_userMode) {
      case UserMode.developer:
        return text('mode_developer');
      case UserMode.technician:
        return text('mode_technician');
      case UserMode.user:
        return text('mode_user');
    }
  }

  Future<void> setMqttConfig({
    required String server,
    required int port,
    required String username,
    required String password,
  }) async {
    _mqttServer = server;
    _mqttPort = port;
    _mqttUsername = username;
    _mqttPassword = password;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('mqttServer', server);
    await prefs.setInt('mqttPort', port);
    await prefs.setString('mqttUsername', username);
    await prefs.setString('mqttPassword', password);
    notifyListeners();
  }

  Future<void> setSuccessNotificationsEnabled(bool enabled) async {
    _enableSuccessNotifications = enabled;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('enableSuccessNotifications', enabled);
    notifyListeners();
  }

  Future<void> setErrorNotificationsEnabled(bool enabled) async {
    _enableErrorNotifications = enabled;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('enableErrorNotifications', enabled);
    notifyListeners();
  }

  Future<void> setLearningNotificationsEnabled(bool enabled) async {
    _enableLearningNotifications = enabled;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('enableLearningNotifications', enabled);
    notifyListeners();
  }

  // Textes traduits
  Map<String, String> get texts {
    if (_language == 'en') {
      return {
        'wavecontrol': 'WaveControl',
        'connected': 'Online',
        'disconnected': 'Offline',
        'configuration': 'Configuration',
        'monitoring': 'Monitoring',
        'reset_periph': 'Reset Devices',
        'test_request': 'Test Request',
        'settings': 'Settings',
        'mqtt_connection': 'MQTT Connection',
        'mqtt_subtitle': 'Configure MQTT server',
        'language': 'Language',
        'theme': 'Theme',
        'light_mode': 'Light mode',
        'dark_mode': 'Dark mode',
        'notifications': 'Notifications',
        'notifications_subtitle': 'Manage notifications',
        'about': 'About',
        'about_subtitle': 'Version and information',
        'mqtt_server': 'MQTT Server',
        'port': 'Port',
        'username': 'Username',
        'password': 'Password',
        'cancel': 'Cancel',
        'save': 'Save',
        'validate': 'Validate',
        'close': 'Close',
        'back': 'Back',
        'next': 'Next',
        'mqtt_saved': 'MQTT configuration saved',
        'mqtt_reconnecting': 'Reconnecting to MQTT server...',
        'mqtt_connected': 'Successfully connected to MQTT server',
        'mqtt_connection_failed': 'Failed to connect to MQTT server',
        'language_changed': 'Language changed to',
        'theme_activated': 'activated',
        'coming_soon': 'Notifications - Coming soon',
        'app_description': 'Authors: Amaury GIELEN, Henry BOISSEL DOMBREVAL, Kacper WOJTOWICZ, Chris EL HELOU, Kylian HORACE - E5FE 2026 - Connected control application for device management using a connected wristband.',
        'no_device': 'No device detected',
        'french': 'French',
        'english': 'English',
        'spanish': 'Spanish',
        'german': 'German',
        'chinese': 'Chinese',
        'history': 'History',
        'no_history': 'No history',
        'clear_history': 'Clear history',
        'restart_required': 'Please restart the application to apply MQTT changes',
        'user_mode': 'User Mode',
        'mode_developer': 'Developer',
        'mode_technician': 'Technician',
        'mode_user': 'User',
        'mode_developer_desc': 'Full access to all features',
        'mode_technician_desc': 'Configuration, Monitoring, Reconnect',
        'mode_user_desc': 'Monitoring and Reconnect only',
        'passwords': 'Access passwords',
        'passwords_subtitle': 'Change developer and technician passwords',
        'developer_password': 'Developer password',
        'technician_password': 'Technician password',
        'current_password': 'Current password',
        'new_password': 'New password',
        'enter_password': 'Enter password',
        'wrong_password': 'Incorrect password',
        'current_password_required': 'Current password required',
        'passwords_updated': 'Passwords updated',
        'leave_empty_keep': 'Leave empty to keep current',
        'movements': 'Movements',
        'surveillance': 'Supervision',
        'control': 'Control',
        'reconnect': 'RECONNECT',
        'test_mqtt': 'TEST.MQTT',
        'connected_label': 'Connected',
        'disconnected_label': 'Disconnected',
        'current_configs': 'Current Configurations',
        'configs_count': 'configuration(s)',
        'no_config': 'No configuration yet',
        'config_loaded': 'Configuration loaded successfully',
        'available_devices': 'View available devices',
        'add_config': 'Configuration',
        'smart_objects': 'Smart Objects',
        'ir_devices': 'Infrared Devices',
        'add_ir': 'Add IR',
        'devices_count': 'device(s)',
        'ir_count': 'remote(s)',
        'app_slogan': 'Intelligent connected control',
        'connecting_bracelet': 'Connecting to bracelet...',
        'no_possibility': 'No possibility detected',
        'no_saved_config': 'No saved configuration',
        'movement_configured': 'error: Movement already configured',
        'action_used': 'error: Action already used on this device',
        'add': 'Add',
        'delete': 'Delete',
        'delete_remote_title': 'Delete',
        'delete_remote_message': 'This remote will be permanently deleted.',
        'button_saved': 'Button saved successfully!',
        'remote_deleted': 'Remote deleted!',
        'add_remote': 'Add a remote',
        'remote_exists': 'This remote already exists!',
        'choose_color': 'Choose a color',
        'adjust_brightness': 'Adjust brightness',
        'close_history': 'Close history',
        'not_connected_mqtt': 'Not connected to MQTT',
        'check_connection': 'check the connection',
        'delete_action_title': 'Delete',
        'delete_action_message': 'This action will be permanently deleted.',
        'no_device_registered': 'No device registered',
        'no_action_saved': 'No action saved',
        'add_device': 'Add a device',
        'enter_name': 'Please enter a name',
        'devices': 'Devices',
        'new_remote': 'New remote',
        'short_name_no_spaces': 'Short name, no spaces (e.g., tv, fan)',
        'remote_name': 'Remote name',
        'light': 'Light',
        'socket': 'Socket',
        'device': 'Device',
        'on': 'On',
        'off': 'Off',
        'brightness': 'Brightness',
        'send_error': 'Send error',
        'parsing_error': 'Parsing error',
        'timeout_bracelet': 'Timeout: no response from bracelet',
        'timeout_station': 'Timeout: no response from base station',
        'config_deleted': 'Configuration deleted',
        'available_devices_title': 'Available devices',
        'which_movement': 'Which movement?',
        'which_device': 'Which device?',
        'which_action': 'Which action?',
        'swipe_to_delete': 'Swipe to delete',
        'add_peripheral': 'Add a peripheral',
        'peripheral_info': 'Peripheral information',
        'peripheral_name': 'Device name',
        'peripheral_name_example': 'e.g., Living Room TV',
        'device_type': 'Device type',
        'select_type': 'Select a type',
        'add_peripheral_button': 'Add peripheral',
        'fill_all_fields': 'Please fill in all fields',
        'ir_type_tv': 'TV',
        'ir_type_air_conditioner': 'Air conditioner',
        'ir_type_ac_unit': 'AC unit',
        'ir_type_lighting': 'Lighting',
        'ir_type_other': 'Other',
        'saved_peripherals': 'Saved peripherals',
        'new_ir_action': 'New IR action',
        'action_name': 'Action name',
        'add_action': 'Add an action',
        'action_exists': 'This action already exists!',
        'action_deleted': 'Action deleted!',
        'action_sent': 'Action sent!',
        'action_added_success': 'Action added successfully!',
        'button_s': 'button(s)',
        'error_loading': 'Loading error',
        'add_remote_dialog': 'Add a remote',
        'remote_name_hint': 'Remote name (e.g., tv, fan)',
        'error_text': 'Error',
        'loaded_configs': 'Configurations loaded',
        'config_ir': 'IR Configuration',
        'error_notifications': 'Error notifications',
        'error_notif_desc': 'Empty names, duplicates, MQTT errors',
        'remote_created': 'Remote created!',
        'action_sent_success': 'Action sent!',
        'command_sent': 'Command sent',
        'command_failed': 'Failed',
        'waiting_ir_command': 'Waiting for the IR command...',
        'point_remote_and_press': 'Point the remote toward the base station and press a button',
        'step_of': 'Step',
        'of': 'of',
        'success_notifications': 'Success notifications',
        'success_notif_desc': 'Buttons/remotes created, actions sent',
        'cancel': 'Cancel',
        'learning_notifications': 'Learning notifications',
        'learning_notif_desc': 'New remote, button learning',
        'learning_ir_in_progress': 'IR learning mode in progress (6 seconds)',
        'notification_settings_title': 'Notification settings',
        'notification_settings_subtitle': 'Choose which notifications to show',
        'remotes_loaded': 'Remotes loaded',
        'remote_deleted_with_name': 'Remote deleted:',
        'refresh': 'Refresh',
        'no_remote_saved': 'No remote saved',
        'chinese': 'Chinese',
        'view_configs': 'View configurations',
        'read_only_mode': 'Read-only mode',
        'loading_configs': 'Loading configurations...',
        'read_only': 'Read-only',
        'config_error': 'Configuration error',
      };
    } else if (_language == 'zh') {
      return {
        'wavecontrol': 'WaveControl',
        'connected': '在线',
        'disconnected': '离线',
        'configuration': '配置',
        'monitoring': '监控',
        'reset_periph': '重置设备',
        'test_request': '测试请求',
        'settings': '设置',
        'mqtt_connection': 'MQTT连接',
        'mqtt_subtitle': '配置MQTT服务器',
        'language': '语言',
        'theme': '主题',
        'light_mode': '浅色模式',
        'dark_mode': '深色模式',
        'notifications': '通知',
        'notifications_subtitle': '管理通知',
        'about': '关于',
        'about_subtitle': '版本和信息',
        'mqtt_server': 'MQTT服务器',
        'port': '端口',
        'username': '用户名',
        'password': '密码',
        'cancel': '取消',
        'save': '保存',
        'validate': '验证',
        'close': '关闭',
        'back': '返回',
        'next': '下一个',
        'mqtt_saved': 'MQTT配置已保存',
        'mqtt_reconnecting': '正在重新连接到MQTT服务器...',
        'mqtt_connected': '成功连接到MQTT服务器',
        'mqtt_connection_failed': '无法连接到MQTT服务器',
        'language_changed': '语言已更改为',
        'theme_activated': '已激活',
        'coming_soon': '通知-即将推出',
        'app_description': '作者：Amaury GIELEN、Henry BOISSEL DOMBREVAL、Kacper WOJTOWICZ、Chris EL HELOU、Kylian HORACE - E5FE 2026 - 连接控制应用程序，用于使用连接腕带进行设备管理。',
        'no_device': '未检测到设备',
        'french': '法语',
        'english': '英语',
        'spanish': '西班牙语',
        'german': '德语',
        'chinese': '中文',
        'history': '历史',
        'no_history': '无历史记录',
        'clear_history': '清除历史记录',
        'restart_required': '请重新启动应用程序以应用MQTT更改',
        'user_mode': '用户模式',
        'mode_developer': '开发者',
        'mode_technician': '技术人员',
        'mode_user': '用户',
        'mode_developer_desc': '完全访问所有功能',
        'mode_technician_desc': '配置、监控、重新连接',
        'mode_user_desc': '仅监控和重新连接',
        'passwords': '访问密码',
        'passwords_subtitle': '更改开发者和技术人员密码',
        'developer_password': '开发者密码',
        'technician_password': '技术人员密码',
        'current_password': '当前密码',
        'new_password': '新密码',
        'enter_password': '输入密码',
        'wrong_password': '密码不正确',
        'current_password_required': '需要当前密码',
        'passwords_updated': '密码已更新',
        'leave_empty_keep': '留空以保留当前',
        'movements': '动作',
        'surveillance': '监督',
        'control': '控制',
        'reconnect': '重新连接',
        'test_mqtt': '测试.MQTT',
        'connected_label': '已连接',
        'disconnected_label': '已断开',
        'current_configs': '当前配置',
        'configs_count': '个配置',
        'no_config': '暂无配置',
        'config_loaded': '配置加载成功',
        'available_devices': '查看可用设备',
        'add_config': '配置',
        'smart_objects': '智能对象',
        'ir_devices': '红外设备',
        'add_ir': '添加IR',
        'devices_count': '个设备',
        'ir_count': '个遥控器',
        'app_slogan': '智能连接控制',
        'connecting_bracelet': '正在连接腕带...',
        'no_possibility': '未检测到任何可能性',
        'no_saved_config': '无保存的配置',
        'movement_configured': '错误：动作已配置',
        'action_used': '错误：此设备上已使用该操作',
        'add': '添加',
        'delete': '删除',
        'delete_remote_title': '删除',
        'delete_remote_message': '此遥控器将被永久删除。',
        'button_saved': '按钮保存成功！',
        'remote_deleted': '遥控器已删除！',
        'add_remote': '添加遥控器',
        'remote_exists': '此遥控器已存在！',
        'choose_color': '选择颜色',
        'adjust_brightness': '调整亮度',
        'close_history': '关闭历史记录',
        'not_connected_mqtt': '未连接到MQTT',
        'check_connection': '检查连接',
        'delete_action_title': '删除',
        'delete_action_message': '此操作将被永久删除。',
        'no_device_registered': '未注册设备',
        'no_action_saved': '未保存任何操作',
        'add_device': '添加设备',
        'enter_name': '请输入名称',
        'devices': '设备',
        'new_remote': '新遥控器',
        'short_name_no_spaces': '简短名称，无空格(例如：电视、风扇)',
        'remote_name': '遥控器名称',
        'light': '灯',
        'socket': '插座',
        'device': '设备',
        'on': '开',
        'off': '关',
        'brightness': '亮度',
        'send_error': '发送错误',
        'parsing_error': '解析错误',
        'timeout_bracelet': '超时：腕带无响应',
        'timeout_station': '超时：基站无响应',
        'config_deleted': '配置已删除',
        'available_devices_title': '可用设备',
        'which_movement': '哪个动作？',
        'which_device': '哪个设备？',
        'which_action': '哪个操作？',
        'swipe_to_delete': '滑动删除',
        'add_peripheral': '添加外设',
        'peripheral_info': '外设信息',
        'peripheral_name': '外设名称',
        'peripheral_name_example': '例如：客厅电视',
        'device_type': '设备类型',
        'select_type': '选择类型',
        'add_peripheral_button': '添加外设',
        'fill_all_fields': '请填写所有字段',
        'ir_type_tv': '电视',
        'ir_type_air_conditioner': '空调',
        'ir_type_ac_unit': '空调机',
        'ir_type_lighting': '照明',
        'ir_type_other': '其他',
        'saved_peripherals': '已保存的外设',
        'new_ir_action': '新红外操作',
        'action_name': '操作名称',
        'add_action': '添加操作',
        'action_exists': '此操作已存在！',
        'action_deleted': '操作已删除！',
        'action_sent': '操作已发送！',
        'action_added_success': '操作添加成功！',
        'button_s': '个按钮',
        'error_loading': '加载错误',
        'add_remote_dialog': '添加遥控器',
        'remote_name_hint': '遥控器名称(例如：电视、风扇)',
        'error_text': '错误',
        'loaded_configs': '已加载配置',
        'config_ir': '红外配置',
        'error_notifications': '错误通知',
        'error_notif_desc': '空名称、重复、MQTT错误',
        'remote_created': '遥控器已创建！',
        'action_sent_success': '操作已发送！',
        'command_sent': '命令已发送',
        'command_failed': '失败',
        'waiting_ir_command': '等待红外命令...',
        'point_remote_and_press': '指向遥控器向基站，然后按下一个按钮',
        'step_of': '步骤',
        'of': '共',
        'success_notifications': '成功通知',
        'success_notif_desc': '按钮/遥控器已创建、操作已发送',
        'cancel': '取消',
        'learning_notifications': '学习通知',
        'learning_notif_desc': '新遥控器、按钮学习',
        'learning_ir_in_progress': '红外学习模式进行中(6秒)',
        'notification_settings_title': '通知设置',
        'notification_settings_subtitle': '选择要显示的通知',
        'remotes_loaded': '遥控器已加载',
        'remote_deleted_with_name': '遥控器已删除：',
        'refresh': '刷新',
        'no_remote_saved': '未保存遥控器',
        'view_configs': '查看配置',
        'read_only_mode': '只读模式',
        'loading_configs': '正在加载配置...',
        'read_only': '只读',
        'config_error': '配置错误',
      };
    } else if (_language == 'es') {
      return {
        'wavecontrol': 'WaveControl',
        'connected': 'En línea',
        'disconnected': 'Fuera de línea',
        'configuration': 'Configuración',
        'monitoring': 'Monitoreo',
        'reset_periph': 'Reiniciar Dispositivos',
        'test_request': 'Solicitud de prueba',
        'settings': 'Ajustes',
        'mqtt_connection': 'Conexión MQTT',
        'mqtt_subtitle': 'Configurar servidor MQTT',
        'language': 'Idioma',
        'theme': 'Tema',
        'light_mode': 'Modo claro',
        'dark_mode': 'Modo oscuro',
        'notifications': 'Notificaciones',
        'notifications_subtitle': 'Gestionar notificaciones',
        'about': 'Acerca de',
        'about_subtitle': 'Versión e información',
        'mqtt_server': 'Servidor MQTT',
        'port': 'Puerto',
        'username': 'Nombre de usuario',
        'password': 'Contraseña',
        'cancel': 'Cancelar',
        'save': 'Guardar',
        'validate': 'Validar',
        'close': 'Cerrar',
        'back': 'Atrás',
        'next': 'Siguiente',
        'mqtt_saved': 'Configuración MQTT guardada',
        'mqtt_reconnecting': 'Reconectando al servidor MQTT...',
        'mqtt_connected': 'Conectado exitosamente al servidor MQTT',
        'mqtt_connection_failed': 'Error al conectar al servidor MQTT',
        'language_changed': 'Idioma cambiado a',
        'theme_activated': 'activado',
        'coming_soon': 'Notificaciones - Próximamente',
        'app_description': 'Autores: Amaury GIELEN, Henry BOISSEL DOMBREVAL, Kacper WOJTOWICZ, Chris EL HELOU, Kylian HORACE - E5FE 2026 - Aplicación de control conectado para la gestión de dispositivos usando una pulsera conectada.',
        'no_device': 'Ningún dispositivo detectado',
        'french': 'Francés',
        'english': 'Inglés',
        'spanish': 'Español',
        'german': 'Alemán',
        'chinese': 'Chino',
        'history': 'Historial',
        'no_history': 'Sin historial',
        'clear_history': 'Borrar historial',
        'restart_required': 'Por favor, reinicie la aplicación para aplicar los cambios de MQTT',
        'user_mode': 'Modo de usuario',
        'mode_developer': 'Desarrollador',
        'mode_technician': 'Técnico',
        'mode_user': 'Usuario',
        'mode_developer_desc': 'Acceso completo a todas las funciones',
        'mode_technician_desc': 'Configuración, Monitoreo, Reconectar',
        'mode_user_desc': 'Solo Monitoreo y Reconectar',
        'passwords': 'Contraseñas de acceso',
        'passwords_subtitle': 'Cambiar contraseñas de desarrollador y técnico',
        'developer_password': 'Contraseña de desarrollador',
        'technician_password': 'Contraseña de técnico',
        'current_password': 'Contraseña actual',
        'new_password': 'Nueva contraseña',
        'enter_password': 'Ingrese contraseña',
        'wrong_password': 'Contraseña incorrecta',
        'current_password_required': 'Se requiere contraseña actual',
        'passwords_updated': 'Contraseñas actualizadas',
        'leave_empty_keep': 'Dejar vacío para mantener la actual',
        'movements': 'Movimientos',
        'surveillance': 'Supervisión',
        'control': 'Control',
        'reconnect': 'RECONECTAR',
        'test_mqtt': 'PROBAR.MQTT',
        'connected_label': 'Conectado',
        'disconnected_label': 'Desconectado',
        'current_configs': 'Configuraciones actuales',
        'configs_count': 'configuración(es)',
        'no_config': 'Ninguna configuración aún',
        'config_loaded': 'Configuración cargada exitosamente',
        'available_devices': 'Ver dispositivos disponibles',
        'add_config': 'Configuración',
        'smart_objects': 'Objetos inteligentes',
        'ir_devices': 'Dispositivos infrarrojos',
        'add_ir': 'Agregar IR',
        'devices_count': 'dispositivo(s)',
        'ir_count': 'control(es) remoto(s)',
        'app_slogan': 'Control conectado inteligente',
        'connecting_bracelet': 'Conectando a la pulsera...',
        'no_possibility': 'Ninguna posibilidad detectada',
        'no_saved_config': 'Ninguna configuración guardada',
        'movement_configured': 'error: Movimiento ya configurado',
        'action_used': 'error: Acción ya usada en este dispositivo',
        'add': 'Agregar',
        'delete': 'Eliminar',
        'delete_remote_title': 'Eliminar',
        'delete_remote_message': 'Este control remoto se eliminará permanentemente.',
        'button_saved': '¡Botón guardado exitosamente!',
        'remote_deleted': '¡Control remoto eliminado!',
        'add_remote': 'Agregar un control remoto',
        'remote_exists': '¡Este control remoto ya existe!',
        'choose_color': 'Elegir un color',
        'adjust_brightness': 'Ajustar brillo',
        'close_history': 'Cerrar historial',
        'not_connected_mqtt': 'No conectado a MQTT',
        'check_connection': 'verificar la conexión',
        'delete_action_title': 'Eliminar',
        'delete_action_message': 'Esta acción se eliminará permanentemente.',
        'no_device_registered': 'Ningún dispositivo registrado',
        'no_action_saved': 'Ninguna acción guardada',
        'add_device': 'Agregar un dispositivo',
        'enter_name': 'Por favor ingrese un nombre',
        'devices': 'Dispositivos',
        'new_remote': 'Nuevo control remoto',
        'short_name_no_spaces': 'Nombre corto, sin espacios (ej: tv, ventilador)',
        'remote_name': 'Nombre del control remoto',
        'light': 'Luz',
        'socket': 'Enchufe',
        'device': 'Dispositivo',
        'on': 'Encender',
        'off': 'Apagar',
        'brightness': 'Brillo',
        'send_error': 'Error de envío',
        'parsing_error': 'Error de análisis',
        'timeout_bracelet': 'Tiempo de espera: sin respuesta de la pulsera',
        'timeout_station': 'Tiempo de espera: sin respuesta de la estación base',
        'config_deleted': 'Configuración eliminada',
        'available_devices_title': 'Dispositivos disponibles',
        'which_movement': '¿Qué movimiento?',
        'which_device': '¿Qué dispositivo?',
        'which_action': '¿Qué acción?',
        'swipe_to_delete': 'Deslizar para eliminar',
        'add_peripheral': 'Agregar un periférico',
        'peripheral_info': 'Información del periférico',
        'peripheral_name': 'Nombre del dispositivo',
        'peripheral_name_example': 'ej., TV de la sala',
        'device_type': 'Tipo de dispositivo',
        'select_type': 'Seleccionar un tipo',
        'add_peripheral_button': 'Agregar periférico',
        'fill_all_fields': 'Por favor complete todos los campos',
        'ir_type_tv': 'TV',
        'ir_type_air_conditioner': 'Aire acondicionado',
        'ir_type_ac_unit': 'Unidad de AC',
        'ir_type_lighting': 'Iluminación',
        'ir_type_other': 'Otro',
        'saved_peripherals': 'Periféricos guardados',
        'new_ir_action': 'Nueva acción IR',
        'action_name': 'Nombre de la acción',
        'add_action': 'Agregar una acción',
        'action_exists': '¡Esta acción ya existe!',
        'action_deleted': '¡Acción eliminada!',
        'action_sent': '¡Acción enviada!',
        'action_added_success': '¡Acción agregada exitosamente!',
        'button_s': 'botón(es)',
        'error_loading': 'Error de carga',
        'add_remote_dialog': 'Agregar un control remoto',
        'remote_name_hint': 'Nombre del control remoto (ej: tv, ventilador)',
        'error_text': 'Error',
        'loaded_configs': 'Configuraciones cargadas',
        'config_ir': 'Configuración IR',
        'error_notifications': 'Notificaciones de error',
        'error_notif_desc': 'Nombres vacíos, duplicados, errores MQTT',
        'remote_created': '¡Control remoto creado!',
        'action_sent_success': '¡Acción enviada!',
        'command_sent': 'Comando enviado',
        'command_failed': 'Fallido',
        'waiting_ir_command': 'Esperando el comando IR...',
        'point_remote_and_press': 'Apunte el control remoto hacia la estación base y presione un botón',
        'step_of': 'Paso',
        'of': 'de',
        'success_notifications': 'Notificaciones de éxito',
        'success_notif_desc': 'Botones/controles remotos creados, acciones enviadas',
        'cancel': 'Cancelar',
        'learning_notifications': 'Notificaciones de aprendizaje',
        'learning_notif_desc': 'Nuevo control remoto, aprendizaje de botón',
        'learning_ir_in_progress': 'Modo de aprendizaje IR en progreso (6 segundos)',
        'notification_settings_title': 'Configuración de notificaciones',
        'notification_settings_subtitle': 'Elegir qué notificaciones mostrar',
        'remotes_loaded': 'Controles remotos cargados',
        'remote_deleted_with_name': 'Control remoto eliminado:',
        'refresh': 'Actualizar',
        'no_remote_saved': 'Ningún control remoto guardado',
        'view_configs': 'Ver configuraciones',
        'read_only_mode': 'Modo de solo lectura',
        'loading_configs': 'Cargando configuraciones...',
        'read_only': 'Solo lectura',
        'config_error': 'Error de configuración',
      };
    } else if (_language == 'de') {
      return {
        'wavecontrol': 'WaveControl',
        'connected': 'Online',
        'disconnected': 'Offline',
        'configuration': 'Konfiguration',
        'monitoring': 'Überwachung',
        'reset_periph': 'Geräte zurücksetzen',
        'test_request': 'Testanfrage',
        'settings': 'Einstellungen',
        'mqtt_connection': 'MQTT-Verbindung',
        'mqtt_subtitle': 'MQTT-Server konfigurieren',
        'language': 'Sprache',
        'theme': 'Thema',
        'light_mode': 'Heller Modus',
        'dark_mode': 'Dunkler Modus',
        'notifications': 'Benachrichtigungen',
        'notifications_subtitle': 'Benachrichtigungen verwalten',
        'about': 'Über',
        'about_subtitle': 'Version und Informationen',
        'mqtt_server': 'MQTT-Server',
        'port': 'Port',
        'username': 'Benutzername',
        'password': 'Passwort',
        'cancel': 'Abbrechen',
        'save': 'Speichern',
        'validate': 'Validieren',
        'close': 'Schließen',
        'back': 'Zurück',
        'next': 'Weiter',
        'mqtt_saved': 'MQTT-Konfiguration gespeichert',
        'mqtt_reconnecting': 'Verbindung zum MQTT-Server wird wiederhergestellt...',
        'mqtt_connected': 'Erfolgreich mit MQTT-Server verbunden',
        'mqtt_connection_failed': 'Verbindung zum MQTT-Server fehlgeschlagen',
        'language_changed': 'Sprache geändert zu',
        'theme_activated': 'aktiviert',
        'coming_soon': 'Benachrichtigungen - Demnächst',
        'app_description': 'Autoren: Amaury GIELEN, Henry BOISSEL DOMBREVAL, Kacper WOJTOWICZ, Chris EL HELOU, Kylian HORACE - E5FE 2026 - Vernetzte Steuerungsanwendung für die Geräteverwaltung mit einem verbundenen Armband.',
        'no_device': 'Kein Gerät erkannt',
        'french': 'Französisch',
        'english': 'Englisch',
        'spanish': 'Spanisch',
        'german': 'Deutsch',
        'chinese': 'Chinesisch',
        'history': 'Verlauf',
        'no_history': 'Kein Verlauf',
        'clear_history': 'Verlauf löschen',
        'restart_required': 'Bitte starten Sie die Anwendung neu, um MQTT-Änderungen anzuwenden',
        'user_mode': 'Benutzermodus',
        'mode_developer': 'Entwickler',
        'mode_technician': 'Techniker',
        'mode_user': 'Benutzer',
        'mode_developer_desc': 'Vollzugriff auf alle Funktionen',
        'mode_technician_desc': 'Konfiguration, Überwachung, Neuverbindung',
        'mode_user_desc': 'Nur Überwachung und Neuverbindung',
        'passwords': 'Zugriffspasswörter',
        'passwords_subtitle': 'Entwickler- und Techniker-Passwörter ändern',
        'developer_password': 'Entwickler-Passwort',
        'technician_password': 'Techniker-Passwort',
        'current_password': 'Aktuelles Passwort',
        'new_password': 'Neues Passwort',
        'enter_password': 'Passwort eingeben',
        'wrong_password': 'Falsches Passwort',
        'current_password_required': 'Aktuelles Passwort erforderlich',
        'passwords_updated': 'Passwörter aktualisiert',
        'leave_empty_keep': 'Leer lassen, um das aktuelle beizubehalten',
        'movements': 'Bewegungen',
        'surveillance': 'Überwachung',
        'control': 'Steuerung',
        'reconnect': 'NEU VERBINDEN',
        'test_mqtt': 'TEST.MQTT',
        'connected_label': 'Verbunden',
        'disconnected_label': 'Getrennt',
        'current_configs': 'Aktuelle Konfigurationen',
        'configs_count': 'Konfiguration(en)',
        'no_config': 'Noch keine Konfiguration',
        'config_loaded': 'Konfiguration erfolgreich geladen',
        'available_devices': 'Verfügbare Geräte anzeigen',
        'add_config': 'Konfiguration',
        'smart_objects': 'Intelligente Objekte',
        'ir_devices': 'Infrarot-Geräte',
        'add_ir': 'IR hinzufügen',
        'devices_count': 'Gerät(e)',
        'ir_count': 'Fernbedienung(en)',
        'app_slogan': 'Intelligente vernetzte Steuerung',
        'connecting_bracelet': 'Verbindung zum Armband wird hergestellt...',
        'no_possibility': 'Keine Möglichkeit erkannt',
        'no_saved_config': 'Keine gespeicherte Konfiguration',
        'movement_configured': 'Fehler: Bewegung bereits konfiguriert',
        'action_used': 'Fehler: Aktion bereits auf diesem Gerät verwendet',
        'add': 'Hinzufügen',
        'delete': 'Löschen',
        'delete_remote_title': 'Löschen',
        'delete_remote_message': 'Diese Fernbedienung wird dauerhaft gelöscht.',
        'button_saved': 'Taste erfolgreich gespeichert!',
        'remote_deleted': 'Fernbedienung gelöscht!',
        'add_remote': 'Fernbedienung hinzufügen',
        'remote_exists': 'Diese Fernbedienung existiert bereits!',
        'choose_color': 'Farbe wählen',
        'adjust_brightness': 'Helligkeit anpassen',
        'close_history': 'Verlauf schließen',
        'not_connected_mqtt': 'Nicht mit MQTT verbunden',
        'check_connection': 'Verbindung überprüfen',
        'delete_action_title': 'Löschen',
        'delete_action_message': 'Diese Aktion wird dauerhaft gelöscht.',
        'no_device_registered': 'Kein Gerät registriert',
        'no_action_saved': 'Keine Aktion gespeichert',
        'add_device': 'Gerät hinzufügen',
        'enter_name': 'Bitte geben Sie einen Namen ein',
        'devices': 'Geräte',
        'new_remote': 'Neue Fernbedienung',
        'short_name_no_spaces': 'Kurzer Name, keine Leerzeichen (z.B. tv, ventilator)',
        'remote_name': 'Name der Fernbedienung',
        'light': 'Licht',
        'socket': 'Steckdose',
        'device': 'Gerät',
        'on': 'Ein',
        'off': 'Aus',
        'brightness': 'Helligkeit',
        'send_error': 'Sendefehler',
        'parsing_error': 'Parsing-Fehler',
        'timeout_bracelet': 'Zeitüberschreitung: keine Antwort vom Armband',
        'timeout_station': 'Zeitüberschreitung: keine Antwort von der Basisstation',
        'config_deleted': 'Konfiguration gelöscht',
        'available_devices_title': 'Verfügbare Geräte',
        'which_movement': 'Welche Bewegung?',
        'which_device': 'Welches Gerät?',
        'which_action': 'Welche Aktion?',
        'swipe_to_delete': 'Zum Löschen wischen',
        'add_peripheral': 'Peripheriegerät hinzufügen',
        'peripheral_info': 'Peripheriegerät-Informationen',
        'peripheral_name': 'Gerätename',
        'peripheral_name_example': 'z.B. Wohnzimmer-TV',
        'device_type': 'Gerätetyp',
        'select_type': 'Typ auswählen',
        'add_peripheral_button': 'Peripheriegerät hinzufügen',
        'fill_all_fields': 'Bitte füllen Sie alle Felder aus',
        'ir_type_tv': 'TV',
        'ir_type_air_conditioner': 'Klimaanlage',
        'ir_type_ac_unit': 'Klimagerät',
        'ir_type_lighting': 'Beleuchtung',
        'ir_type_other': 'Andere',
        'saved_peripherals': 'Gespeicherte Peripheriegeräte',
        'new_ir_action': 'Neue IR-Aktion',
        'action_name': 'Aktionsname',
        'add_action': 'Aktion hinzufügen',
        'action_exists': 'Diese Aktion existiert bereits!',
        'action_deleted': 'Aktion gelöscht!',
        'action_sent': 'Aktion gesendet!',
        'action_added_success': 'Aktion erfolgreich hinzugefügt!',
        'button_s': 'Taste(n)',
        'error_loading': 'Ladefehler',
        'add_remote_dialog': 'Fernbedienung hinzufügen',
        'remote_name_hint': 'Name der Fernbedienung (z.B. tv, ventilator)',
        'error_text': 'Fehler',
        'loaded_configs': 'Konfigurationen geladen',
        'config_ir': 'IR-Konfiguration',
        'error_notifications': 'Fehlerbenachrichtigungen',
        'error_notif_desc': 'Leere Namen, Duplikate, MQTT-Fehler',
        'remote_created': 'Fernbedienung erstellt!',
        'action_sent_success': 'Aktion gesendet!',
        'command_sent': 'Befehl gesendet',
        'command_failed': 'Fehlgeschlagen',
        'waiting_ir_command': 'Warte auf IR-Befehl...',
        'point_remote_and_press': 'Richten Sie die Fernbedienung auf die Basisstation und drücken Sie eine Taste',
        'step_of': 'Schritt',
        'of': 'von',
        'success_notifications': 'Erfolgsbenachrichtigungen',
        'success_notif_desc': 'Tasten/Fernbedienungen erstellt, Aktionen gesendet',
        'cancel': 'Abbrechen',
        'learning_notifications': 'Lern-Benachrichtigungen',
        'learning_notif_desc': 'Neue Fernbedienung, Tasten-Lernen',
        'learning_ir_in_progress': 'IR-Lernmodus läuft (6 Sekunden)',
        'notification_settings_title': 'Benachrichtigungseinstellungen',
        'notification_settings_subtitle': 'Wählen Sie, welche Benachrichtigungen angezeigt werden sollen',
        'remotes_loaded': 'Fernbedienungen geladen',
        'remote_deleted_with_name': 'Fernbedienung gelöscht:',
        'refresh': 'Aktualisieren',
        'no_remote_saved': 'Keine Fernbedienung gespeichert',
        'view_configs': 'Konfigurationen anzeigen',
        'read_only_mode': 'Nur-Lese-Modus',
        'loading_configs': 'Konfigurationen werden geladen...',
        'read_only': 'Nur lesen',
        'config_error': 'Konfigurationsfehler',
      };
    } else {
      return {
        'wavecontrol': 'WaveControl',
        'connected': 'En ligne',
        'disconnected': 'Hors ligne',
        'configuration': 'Configuration',
        'monitoring': 'Monitoring',
        'reset_periph': 'Reset Périph',
        'test_request': 'Test Request',
        'settings': 'Paramètres',
        'mqtt_connection': 'Connexion MQTT',
        'mqtt_subtitle': 'Configurer le serveur MQTT',
        'language': 'Langue',
        'theme': 'Thème',
        'light_mode': 'Mode clair',
        'dark_mode': 'Mode sombre',
        'notifications': 'Notifications',
        'notifications_subtitle': 'Gérer les notifications',
        'about': 'À propos',
        'about_subtitle': 'Version et informations',
        'mqtt_server': 'Serveur MQTT',
        'port': 'Port',
        'username': 'Nom d\'utilisateur',
        'password': 'Mot de passe',
        'cancel': 'Annuler',
        'save': 'Enregistrer',
        'validate': 'Valider',
        'close': 'Fermer',
        'back': 'Retour',
        'next': 'Suivant',
        'mqtt_saved': 'Configuration MQTT enregistrée',
        'mqtt_reconnecting': 'Reconnexion au serveur MQTT...',
        'mqtt_connected': 'Connexion au serveur MQTT réussie',
        'mqtt_connection_failed': 'Échec de connexion au serveur MQTT',
        'language_changed': 'Langue changée en',
        'theme_activated': 'activé',
        'coming_soon': 'Notifications - Fonctionnalité à venir',
        'app_description': 'Auteurs : Amaury GIELEN, Henry BOISSEL DOMBREVAL, Kacper WOJTOWICZ, Chris EL HELOU, Kylian HORACE - E5FE 2026 - Application de contrôle connecté pour la gestion de périphériques à l\'aide d\'un bracelet connecté. ',
        'no_device': 'Aucun périphérique détecté',
        'french': 'Français',
        'english': 'English',
        'spanish': 'Español',
        'german': 'Deutsch',
        'chinese': 'Chinois',
        'history': 'Historique',
        'no_history': 'Pas d\'historique',
        'clear_history': 'Effacer l\'historique',
        'restart_required': 'Veuillez redémarrer l\'application pour appliquer les changements MQTT',
        'user_mode': 'Mode utilisateur',
        'mode_developer': 'Développeur',
        'mode_technician': 'Technicien',
        'mode_user': 'Utilisateur',
        'mode_developer_desc': 'Accès complet à toutes les fonctionnalités',
        'mode_technician_desc': 'Configuration, Monitoring, Reconnecte',
        'mode_user_desc': 'Monitoring et Reconnecte uniquement',
        'passwords': 'Mots de passe d\'accès',
        'passwords_subtitle': 'Changer les mots de passe développeur et technicien',
        'developer_password': 'Mot de passe développeur',
        'technician_password': 'Mot de passe technicien',
        'current_password': 'Mot de passe actuel',
        'new_password': 'Nouveau mot de passe',
        'enter_password': 'Saisir le mot de passe',
        'wrong_password': 'Mot de passe incorrect',
        'current_password_required': 'Mot de passe actuel requis',
        'passwords_updated': 'Mots de passe mis à jour',
        'leave_empty_keep': 'Laisser vide pour garder l\'actuel',
        'movements': 'Mouvements',
        'surveillance': 'Surveillance',
        'control': 'Contrôle',
        'reconnect': 'RECONNECT',
        'test_mqtt': 'TEST.MQTT',
        'connected_label': 'Connecté',
        'disconnected_label': 'Déconnecté',
        'current_configs': 'Configurations actuelles',
        'configs_count': 'configuration(s)',
        'no_config': 'Aucune configuration pour le moment',
        'config_loaded': 'Configuration chargée avec succès',
        'available_devices': 'Voir les périphériques disponibles',
        'add_config': 'Configuration',
        'smart_objects': 'Objets intelligents',
        'ir_devices': 'Périphériques infrarouges',
        'add_ir': 'Ajouter IR',
        'devices_count': 'appareil(s)',
        'ir_count': 'télécommande(s)',
        'app_slogan': 'Contrôle connecté intelligent',
        'connecting_bracelet': 'Connexion au bracelet...',
        'no_possibility': 'Aucune possibilité détectée',
        'no_saved_config': 'Aucune configuration enregistrée',
        'movement_configured': 'error: Mouvement déjà configuré',
        'action_used': 'error: Action déjà utilisée sur ce périphérique',
        'add': 'Ajouter',
        'delete': 'Supprimer',
        'delete_remote_title': 'Supprimer',
        'delete_remote_message': 'Cette télécommande sera définitivement supprimée.',
        'button_saved': 'Bouton enregistré avec succès !',
        'remote_deleted': 'Télécommande supprimée !',
        'add_remote': 'Ajouter une télécommande',
        'remote_exists': 'Cette télécommande existe déjà !',
        'choose_color': 'Choisir une couleur',
        'adjust_brightness': 'Régler la luminosité',
        'close_history': 'Fermer l\'historique',
        'not_connected_mqtt': 'Non connecté au MQTT',
        'check_connection': 'vérifiez la connexion',
        'delete_action_title': 'Supprimer',
        'delete_action_message': 'Cette action sera définitivement supprimée.',
        'no_device_registered': 'Aucun périphérique enregistré',
        'no_action_saved': 'Aucune action enregistrée',
        'add_device': 'Ajouter un périphérique',
        'enter_name': 'Veuillez saisir un nom',
        'devices': 'Périphériques',
        'new_remote': 'Nouvelle télécommande',
        'short_name_no_spaces': 'Nom court, sans espaces (ex: tv, fan)',
        'remote_name': 'Nom de la télécommande',
        'light': 'Lumiere',
        'socket': 'Prise',
        'device': 'Appareil',
        'on': 'Allume',
        'off': 'Eteint',
        'brightness': 'Luminosite',
        'send_error': 'Erreur d\'envoi',
        'parsing_error': 'Erreur de parsing',
        'timeout_bracelet': 'Timeout: pas de réponse du bracelet',
        'timeout_station': 'Timeout: pas de réponse de la base station',
        'config_deleted': 'Configuration supprimée',
        'available_devices_title': 'Périphériques disponibles',
        'which_movement': 'Quel mouvement ?',
        'which_device': 'Quel appareil ?',
        'which_action': 'Quelle action ?',
        'swipe_to_delete': 'Glissez pour supprimer',
        'add_peripheral': 'Ajouter un Périphérique',
        'peripheral_info': 'Informations du Périphérique',
        'peripheral_name': 'Nom du périphérique',
        'peripheral_name_example': 'Ex: TV Salon',
        'device_type': 'Type de périphérique',
        'select_type': 'Sélectionner un type',
        'add_peripheral_button': 'Ajouter le Périphérique',
        'fill_all_fields': 'Veuillez remplir tous les champs',
        'ir_type_tv': 'Télévision',
        'ir_type_air_conditioner': 'Air Conditionné',
        'ir_type_ac_unit': 'Climatiseur',
        'ir_type_lighting': 'Éclairage',
        'ir_type_other': 'Autre',
        'saved_peripherals': 'Périphériques Enregistrés',
        'new_ir_action': 'Nouvelle action IR',
        'action_name': 'Nom de l\'action',
        'add_action': 'Ajouter une action',
        'action_exists': 'Cette action existe déjà !',
        'action_deleted': 'Action supprimée !',
        'action_sent': 'Action envoyée !',
        'action_added_success': 'Action ajoutée avec succès !',
        'button_s': 'bouton(s)',
        'error_loading': 'Erreur de chargement',
        'add_remote_dialog': 'Ajouter une télécommande',
        'remote_name_hint': 'Nom de la télécommande (ex: tv, fan)',
        'error_text': 'Erreur',
        'loaded_configs': 'Configurations chargées',
        'config_ir': 'Configuration IR',
        'error_notifications': 'Notifications d\'erreur',
        'error_notif_desc': 'Noms vides, doublons, erreurs MQTT',
        'remote_created': 'Télécommande créée !',
        'action_sent_success': 'Action envoyée !',
        'command_sent': 'Commande envoyée',
        'command_failed': 'Échec',
        'waiting_ir_command': 'En attente de la commande infrarouge...',
        'point_remote_and_press': 'Pointez la télécommande vers la basestation et appuyez sur un bouton',
        'step_of': 'Étape',
        'of': 'sur',
        'success_notifications': 'Notifications de succès',
        'success_notif_desc': 'Boutons/télécommandes créées, actions envoyées',
        'cancel': 'Annuler',
        'learning_notifications': 'Notifications d\'apprentissage',
        'learning_notif_desc': 'Nouvelle télécommande, apprentissage bouton',
        'learning_ir_in_progress': 'Mode apprentissage IR en cours (6 secondes)',
        'notification_settings_title': 'Paramètres de notifications',
        'notification_settings_subtitle': 'Choisissez les notifications à afficher',
        'remotes_loaded': 'Télécommandes chargées',
        'remote_deleted_with_name': 'Télécommande supprimée :',
        'refresh': 'Actualiser',
        'no_remote_saved': 'Aucune télécommande enregistrée',
        'chinese': 'Chinois',
        'view_configs': 'Voir les configurations',
        'read_only_mode': 'Mode lecture seule',
        'loading_configs': 'Chargement des configurations...',
        'read_only': 'Lecture seule',
        'config_error': 'Erreur de configuration',
      };
    }
  }

  String text(String key) => texts[key] ?? key;
}
